name: Docker Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # 每日UTC时间12点自动构建
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip tree
          jq --version
          unzip -v

      - name: Prepare content
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          chmod +x download_and_prepare.sh
          ./download_and_prepare.sh || {
            echo "##[error]Preparation failed";
            [ -f debug_response.json ] && cat debug_response.json;
            exit 1;
          }

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dol-container:latest
            ghcr.io/${{ github.repository_owner }}/dol-container:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
