name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq tree unzip
          echo "JQ version: $(jq --version)"

      - name: Prepare content
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          chmod +x download_and_prepare.sh
          ./download_and_prepare.sh || { 
            echo "##[error]Preparation failed";
            cat raw_response.json;
            exit 1;
          }
          tree content

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dol-docker:latest
